name: schedule

on:
  repository_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Dependencies
        run: yarn install
        
      - name: Run Command
        run: |
          git config --local user.email "bfthhome@pm.me"
          git config --local user.name "bfthhome"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          yarn start
          git add -A
          git diff-index --quiet HEAD || git commit -m '微博热搜-实时更新'
          git push
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
